x-logging: &logging
  logging:
    driver: 'json-file'
    options: 
      tag: '{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}'

services:
  mysql:
    <<: *logging
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    restart: always
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  phpmyadmin:
    <<: *logging
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    restart: always
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - UPLOAD_LIMIT=200M
      - PMA_HOST=mysql
    depends_on:
      - mysql
